const util = require('../../utils/util.js')
const request = require('../../utils/request.js')
const app = getApp()
Page({
  data:{ fileInfo:null, filePath:'', progress:0, uploading:false },
  chooseFile(){ wx.chooseMessageFile({ count:1, type:'file', extension:['pdf'], success:res=>{ const f=res.tempFiles[0]; if(!f)return; if(!String(f.name).toLowerCase().endsWith('.pdf')) return util.toast('请选择PDF文件'); if(f.size>20*1024*1024) return util.toast('文件不能超过20MB'); this.setData({ fileInfo:{ name:f.name, size:(f.size/1024/1024).toFixed(2)+' MB' }, filePath:f.path }) } }) },
  async startUpload(){ if(!this.data.filePath)return util.toast('请先选择PDF'); this.setData({ uploading:true, progress:0 }); util.loading('正在解析PDF'); try{ const r=await request.uploadPdf(this.data.filePath,p=>this.setData({progress:p})); if(!request.isSuccess(r))throw new Error(r.message||'解析失败'); const parsed=request.normalizeUploadData(r); let details=parsed.paymentDetails; if(!details.length){ const lr=await request.getPaymentDetailList(wx.getStorageSync('userId')); if(request.isSuccess(lr))details=lr.data||[] } if(!details.length)throw new Error('未提取到缴费明细'); app.globalData.personalInfo=parsed.personalInfo; app.globalData.paymentDetails=details; app.globalData.paymentSummary=util.paymentSummary(details); app.globalData.pdfInfo={ id:parsed.id, fileName:this.data.fileInfo.name, fileSize:this.data.fileInfo.size, parseTime:util.dateTime() }; util.toast('解析成功','success'); wx.navigateTo({ url:'/pages/payment/payment' }) }catch(e){ util.toast(e.message||'解析失败') }finally{ util.hideLoading(); this.setData({ uploading:false }) } },
  useDemo(){ const details=util.demoPayments(); app.globalData.paymentDetails=details; app.globalData.personalInfo=util.normalizePersonalInfo({name:'余雪琴',idCard:'350425197510140726',gender:'女'}); app.globalData.paymentSummary=util.paymentSummary(details); app.globalData.pdfInfo={fileName:'缴费明细_示例.pdf',fileSize:'-',parseTime:util.dateTime()}; wx.navigateTo({url:'/pages/payment/payment'}) }
})
